In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler

In [2]:
df = pd.read_csv("../data/processed/clean_network_data.csv")

df.head()

,Source Port,Destination Port,Protocol,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,443,54865,6,3,2,0,12,0,6,6,...,20,0.0,0.0,0,0,0.0,0.0,0,0,0
1,80,55054,6,109,1,1,6,6,6,6,...,20,0.0,0.0,0,0,0.0,0.0,0,0,0
2,80,55055,6,52,1,1,6,6,6,6,...,20,0.0,0.0,0,0,0.0,0.0,0,0,0
3,443,46236,6,34,1,1,6,6,6,6,...,20,0.0,0.0,0,0,0.0,0.0,0,0,0
4,443,54863,6,3,2,0,12,0,6,6,...,20,0.0,0.0,0,0,0.0,0.0,0,0,0

In [3]:
df.shape

(225711, 81)

In [4]:
X = df.drop("Label", axis=1)
y = df["Label"]

print("Feature shape:", X.shape)
print("Label shape:", y.shape)

Feature shape: (225711, 80)
Label shape: (225711,)

In [6]:
scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

In [7]:
X_scaled = pd.DataFrame(X_scaled, columns=X.columns)

X_scaled.head()

,Source Port,Destination Port,Protocol,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,...,act_data_pkt_fwd,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min
0,-1.640229,2.328296,-0.412314,-0.515259,-0.186424,-0.210206,-0.285450,-0.151994,-0.285699,-0.133993,...,-0.188408,-0.355799,-0.231652,-0.061517,-0.231164,-0.226499,-0.472388,-0.28316,-0.478408,-0.391105
1,-1.655973,2.337865,-0.412314,-0.515256,-0.251258,-0.164243,-0.287296,-0.151841,-0.285699,-0.133993,...,-0.269902,-0.355799,-0.231652,-0.061517,-0.231164,-0.226499,-0.472388,-0.28316,-0.478408,-0.391105
2,-1.655973,2.337915,-0.412314,-0.515258,-0.251258,-0.164243,-0.287296,-0.151841,-0.285699,-0.133993,...,-0.269902,-0.355799,-0.231652,-0.061517,-0.231164,-0.226499,-0.472388,-0.28316,-0.478408,-0.391105
3,-1.640229,1.891428,-0.412314,-0.515258,-0.251258,-0.164243,-0.287296,-0.151841,-0.285699,-0.133993,...,-0.269902,-0.355799,-0.231652,-0.061517,-0.231164,-0.226499,-0.472388,-0.28316,-0.478408,-0.391105
4,-1.640229,2.328195,-0.412314,-0.515259,-0.186424,-0.210206,-0.285450,-0.151994,-0.285699,-0.133993,...,-0.188408,-0.355799,-0.231652,-0.061517,-0.231164,-0.226499,-0.472388,-0.28316,-0.478408,-0.391105

In [8]:
X_scaled.describe()

,Source Port,Destination Port,Protocol,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,...,act_data_pkt_fwd,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min
count,2.257110e+05,2.257110e+05,2.257110e+05,2.257110e+05,2.257110e+05,2.257110e+05,2.257110e+05,2.257110e+05,2.257110e+05,2.257110e+05,...,2.257110e+05,2.257110e+05,2.257110e+05,2.257110e+05,225711.000000,2.257110e+05,2.257110e+05,2.257110e+05,2.257110e+05,2.257110e+05
mean,-1.269282e-16,1.208840e-17,1.531197e-16,8.058931e-18,-1.309576e-17,9.066298e-18,-2.014733e-18,6.044198e-18,3.223572e-17,8.058931e-18,...,2.518416e-18,7.253038e-17,-5.842725e-17,1.813260e-17,0.000000,6.044198e-18,1.611786e-17,-3.223572e-17,2.820626e-17,1.208840e-17
std,1.000002e+00,1.000002e+00,1.000002e+00,1.000002e+00,1.000002e+00,1.000002e+00,1.000002e+00,1.000002e+00,1.000002e+00,1.000002e+00,...,1.000002e+00,1.000002e+00,1.000002e+00,1.000002e+00,1.000002,1.000002e+00,1.000002e+00,1.000002e+00,1.000002e+00,1.000002e+00
min,-1.659443e+00,-4.494010e-01,-1.957981e+00,-5.152595e-01,-2.512579e-01,-2.102058e-01,-2.891424e-01,-1.519938e-01,-2.889175e-01,-1.707268e-01,...,-2.699020e-01,-5.156315e+00,-2.316523e-01,-6.151680e-02,-0.231164,-2.264995e-01,-4.723884e-01,-2.831602e-01,-4.784081e-01,-3.911053e-01
25%,-8.355607e-01,-4.453507e-01,-4.123140e-01,-5.129998e-01,-1.864236e-01,-1.642434e-01,-2.811414e-01,-1.519938e-01,-2.856990e-01,-1.707268e-01,...,-1.884081e-01,-3.557994e-01,-2.316523e-01,-6.151680e-02,-0.231164,-2.264995e-01,-4.723884e-01,-2.831602e-01,-4.784081e-01,-3.911053e-01
50%,5.005079e-01,-4.453507e-01,-4.123140e-01,-4.691654e-01,-1.215894e-01,-2.635596e-02,-2.799105e-01,-1.478124e-01,-2.781893e-01,-1.707268e-01,...,-1.069142e-01,-3.557994e-01,-2.316523e-01,-6.151680e-02,-0.231164,-2.264995e-01,-4.723884e-01,-2.831602e-01,-4.784081e-01,-3.911053e-01
75%,8.690442e-01,-4.453507e-01,-4.123140e-01,-2.359142e-01,8.079037e-03,1.960651e-02,-2.694478e-01,1.437906e-01,-2.706796e-01,-1.339927e-01,...,5.607350e-02,-3.557994e-01,-2.292976e-01,-6.151680e-02,-0.229077,-2.241242e-01,-9.528037e-02,-2.831602e-01,-1.718106e-01,-1.677355e-02
max,1.182931e+00,2.868343e+00,2.421408e+00,3.291115e+00,1.249436e+02,1.350114e+02,5.602881e+01,1.317245e+02,5.976324e+00,8.841380e+00,...,1.570948e+02,7.325026e+00,1.250847e+02,1.877752e+02,110.843272,1.272734e+02,5.018532e+00,4.835298e+00,3.978786e+00,5.659625e+00

In [9]:
X_scaled.to_csv("../data/processed/X_scaled.csv", index=False)

y.to_csv("../data/processed/y_labels.csv", index=False)

print("Feature engineering completed successfully")

Feature engineering completed successfully